# Generated by Django 4.0.1 on 2022-03-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('platform', models.CharField(max_length=256)),
                ('developer', models.CharField(max_length=265)),
                ('publisher', models.CharField(max_length=256)),
                ('first_release_date', models.DateTimeField()),
                ('summary', models.TextField()),
                ('cover', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.genre')),
            ],
        ),
    ]
