# Generated by Django 4.0.1 on 2022-03-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
