# Generated by Django 4.0.1 on 2022-03-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_game_first_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='first_release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
